mysql:
  database: hugo-blog
  username: nmdhlewrprrq8fi96qsy
  password: pscale_pw_pwu3DSbwv5NjnrnLFaoFUqAe6I6L0L9ncl2JrL9cgMa
  dsn: nmdhlewrprrq8fi96qsy:pscale_pw_pwu3DSbwv5NjnrnLFaoFUqAe6I6L0L9ncl2JrL9cgMa@tcp(aws.connect.psdb.cloud)/hugo_blog?tls=true&parseTime=true&charset=utf8mb4
